import 'package:concordia_navigation/models/course.dart';
import 'package:concordia_navigation/services/calendar_service.dart';
import 'package:concordia_navigation/widgets/weekday.dart';
import 'package:flutter/material.dart';
import 'package:concordia_navigation/services/localization.dart';

/// User Schedule Screen
/// This should have no business logic, only handling data generated by service classes and models.
class CourseSchedule extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
        appBar: AppBar(
          title: Text(ConcordiaLocalizations.of(context).schedule),
        ),
        body: FutureBuilder(
            future: CalendarService.getSchedule()
                .then((schedule) => schedule.byWeekday()),
            builder: (context, AsyncSnapshot snapshot) {
              switch (snapshot.connectionState) {
                // Uncompleted State
                case ConnectionState.none:
                  return new Text('Error occurred');
                case ConnectionState.waiting:
                  return Center(child: CircularProgressIndicator());
                  break;
                default:
                  // Completed with error
                  if (snapshot.hasError) {
                    return Container(
                      child: Text("Error Occured"),
                    );
                  }
                  List<Widget> weekdayContainer = [];

                  for (int i = 0; i < 5; i++) {
                    List<Course> courseList = snapshot.data[i];
                    if (courseList.isNotEmpty) {
                      String weekday;
                      if (i == 0) {
                        weekday = "Monday";
                      } else if (i == 1) {
                        weekday = "Tuesday";
                      } else if (i == 2) {
                        weekday = "Wednesday";
                      } else if (i == 3) {
                        weekday = "Thursday";
                      } else {
                        weekday = "Friday";
                      }
                      weekdayContainer.add(Weekday(weekday, courseList));
                    }
                  }
                  return Column(children: weekdayContainer);
              }
            }));
  }
}
