import 'package:concordia_navigation/models/course.dart';
import 'package:concordia_navigation/services/calendar_service.dart';
import 'package:concordia_navigation/services/size_config.dart';
import 'package:concordia_navigation/storage/app_constants.dart';
import 'package:flutter/material.dart';
import 'package:concordia_navigation/services/localization.dart';
import 'package:google_fonts/google_fonts.dart';
import 'package:intl/intl.dart';

/// User Schedule Screen
/// This should have no business logic, only handling data generated by service classes and models.
class CourseSchedule extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return FutureBuilder(
        future: CalendarService.getSchedule()
            .then((schedule) => schedule.byWeekday()),
        builder: (context, AsyncSnapshot snapshot) {
          switch (snapshot.connectionState) {
            // Uncompleted State
            case ConnectionState.none:
              return new Text('Error occurred');
            case ConnectionState.waiting:
              return Center(child: CircularProgressIndicator());
              break;
            default:
              // Completed with error
              if (snapshot.hasError)
                return Container(
                  child: Text("Error Occured"),
                );
          }
          List<Widget> weekdayContainer = [];
          for (int i = 0; i < 5; i++) {
            List<Course> courseList = snapshot.data[i];
            if (courseList.isNotEmpty) {
              String weekday;
              if (i == 0) {
                weekday = "Monday";
              } else if (i == 1) {
                weekday = "Tuesday";
              } else if (i == 2) {
                weekday = "Wednesday";
              } else if (i == 3) {
                weekday = "Thursday";
              } else {
                weekday = "Friday";
              }
              weekdayContainer
                  .add(Text(weekday, style: TextStyle(fontSize: 40.0)));
              weekdayContainer.add(Expanded(
                  child: ListView.builder(
                itemCount: courseList.length,
                itemBuilder: (BuildContext context, index) {
                  return Container(
                    decoration: BoxDecoration(
                      color: offWhiteColor,
                      border: Border(
                        bottom: BorderSide(width: 1.0, color: lightGreyColor),
                      ),
                    ),
                    height: 100,
                    child: ListTile(
                      contentPadding: EdgeInsets.only(
                          left: SizeConfig.safeBlockHorizontal * 5.0,
                          right: SizeConfig.safeBlockHorizontal * 5.0),
                      leading: Icon(Icons.school),
                      title: Text(
                        courseList[index].summary,
                      ),
                      subtitle: Text(
                        "${courseList[index].start.hour}:${courseList[index].start.minute}", // print the course's summary
                      ),
                    ),
                  );
                },
              )));
            }
          }

          return Scaffold(
            appBar: AppBar(
              title: Text(
                ConcordiaLocalizations.of(context).schedule,
              ),
              backgroundColor: greenColor,
            ),
            body: Column(
              children: weekdayContainer,
            ),
          );
        });
  }
}
